// This file is automatically generated by the Firebase Studio.
// Do not edit this file.

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  apiKey: "AIzaSyBhbqKeMcYWXQAwkD7va2nxwlhfAljFjWc",
  authDomain: "ts-v3-178ca.firebaseapp.com",
  projectId: "ts-v3-178ca",
  storageBucket: "ts-v3-178ca.firebasestorage.app",
  messagingSenderId: "777806440428",
  appId: "1:777806440428:web:798832102262e41a6942c9",
  measurementId: "G-0WLC7N75K9"
};
